#!/bin/bash
./docker1 swarm init \
    --advertise-addr 127.0.0.1 \
    --listen-addr 127.0.0.1:4374 >token.txt

cat token.txt | grep SWMTKN | awk '{print $5 " " $6}' >token

./docker2 swarm join \
    --token $(cat token)

./docker3 swarm join \
    --token $(cat token)

./docker1 node update --label-add name=docker1 $(./docker1 system info 2>/dev/null | grep NodeID: | awk '{print $2}')
./docker1 node update --label-add name=docker2 $(./docker2 system info 2>/dev/null | grep NodeID: | awk '{print $2}')
./docker1 node update --label-add name=docker3 $(./docker3 system info 2>/dev/null | grep NodeID: | awk '{print $2}')
