version: "3.8"

services:
  mongo1:
    image: localhost:5100/mongo:6.0
    ports:
      - 27017:27017
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.name == docker1
  mongo2:
    image: localhost:5100/mongo:6.0
    ports:
      - 27018:27017
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.name == docker2
  mongo3:
    image: localhost:5100/mongo:6.0
    ports:
      - 27019:27017
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.name == docker3