version: "3.8"

volumes:
  registry_volume:

services:
  registry:
    image: registry:2
    volumes:
      - registry_volume:/var/lib/registry 
    ports:
      - 5100:5000
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.name == docker1